---
- iptables:
    chain: INPUT
    table: filter
    jump: ACCEPT
    protocol: tcp
    destination: 80
    comment: 'Accept all HTTP traffic'

- iptables:
    chain: INPUT
    table: filter
    jump: ACCEPT
    protocol: tcp
    destination: 443
    comment: 'Accept all HTTPS traffic'

- iptables:
    chain: INPUT
    table: filter
    jump: ACCEPT
    protocol: tcp
    destination: 8888
    comment: 'Accept all Crane traffic'
