---
- iptables_raw:
    name: allow_tcp_80
    rules: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'

- iptables_raw:
    name: allow_tcp_443
    rules: '-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT'

- iptables_raw:
    name: allow_tcp_8888
    rules: '-A INPUT -p tcp -m tcp --dport 8888 -j ACCEPT'
