---
- file:
    path: /var/lib/pulp
    state: present
    owner: apache
    group: apache
    mode: 0755
  tags: 
    - mount

- mount:
    path: /var/lib/pulp
    src: {{nfs_mount}} 
    state: present
  tags: 
    - mount
